### ISSUE TITLE
Tree items disappearing

### ISSUE THREAD

**Issue by nevf** [elbywan/bosket#1]
Clicking around tree items in the Riot.js demo, items sometimes disappear completely or move to another branch in the tree.

**Comment by elbywan** [comment]
Thanks for the report !

Could you tell me which demo ? The "nested items" one ?

Also, could it be a trackpad issue that drags and drops the items because of a quick double click or something like that ?

**Comment by nevf** [comment]
@elbywan I'm using https://elbywan.github.io/bosket/riot/index.html#TreeView#Demo

I've tried this again and it is happening when an item is dragged sideways just a small amount. Which can happen on a click of touchpad touch.

**Comment by elbywan** [comment]
@nevf I just managed to reproduce, it happens when dragging an item and dropping it very quickly.

Will fix it ASAP, thanks for raising the issue 👍
