### ISSUE TITLE
Expand/Open a node programmatically

### ISSUE THREAD

**Issue by awallat** [elbywan/bosket#10]
Is there a way to expand a node programmatically? It's an important feature especially if you want to open a certain tree path and select a certain sub-node.

Do you have any ideas? I'm using the angular implementation.

**Comment by elbywan** [comment]
Hello @awallat

> Is there a way to expand a node programmatically?

Yes, to achieve that you have to tinker with the <a href="https://elbywan.github.io/bosket/angular/index.html#TreeView#Optional properties#strategies">fold</a> strategy property, which controls whether a node is expanded.

I think the simplest way to do it would be something like :
```typescript
import { Component } from "@angular/core"
// Tree data structure utility methods
import { tree } from "bosket/tools"

@Component({
    selector: "expandable-tree",
    template: `
        <div>
            <div>
                <button (click)="onSelect([])">none</button>
                <button *ngFor="let item of flattenedModel()" (click)="onSelect([item])">{{ item.label }}</button>
            </div>
            <TreeView
                [model]="model"
                category="children"
                [(selection)]="selection"
                [display]="display"
                [strategies]="strategies">
            </TreeView>
        </div>
    `,
    styles: [`
        >>> .selected > .item {
            color: red;
        }
    `]
})
export class ExpandableTree {
    category = "children"
    selection = []
    onSelect = _ => this.selection = _
    model = [
        { label: 1, children: [
            { label: 2 },
            { label: 3 },
            { label: 4 }
        ]},
        { label: 5, children: [
            { label: 6 },
            { label: 7 },
            { label: 8, children: [
                { label: 9 },
                { label: 10}
            ]}
        ]}
    ]
    display = i => i.label
    // The "no child selection" prevents folding when a child is selected
    strategies = { selection: ["single"], fold: [ "no-child-selection" ]}
    // Flattens the tree into a single array
    flattenedModel() { return tree(this.model, this.category).flatten().sort((a, b) => a.label > b.label) }
}
```

And a little gif of the tree in action :

![gif](https://image.ibb.co/hnwk8w/Kapture_2017_09_29_at_8_53_29.gif)

**Comment by awallat** [comment]
Wow, thank you very much for this hint!!! (also for the nice GIF)
It helped me to write my own folding strategy, the way I need it. Would be good if this will be found in the documentation some day, with an example. So thanks again!

**Comment by elbywan** [comment]
You're welcome :) !

>Would be good if this will be found in the documentation some day, with an example.

Yes I'm planning to make some faq with tree examples (orderable, expandable ...) in the future.
