### ISSUE TITLE
Opener before/after option

### ISSUE THREAD

**Issue by fabien** [elbywan/bosket#13]
Hi @elbywan - would it be possible to add an option to position the opener before the `displayTag` component? Here: 

https://github.com/elbywan/bosket/blob/master/src/riot/components/TreeViewNode.tag#L25

I've switched to a flexbox-based layout right now, to change the order of elements, but it feels like a hack right now.

**Comment by elbywan** [comment]
Done !

Check out <a href="https://elbywan.github.io/bosket/riot/index.html#TreeView#Optional properties#openeropts">the docs (optional properties -> openeropts)</a>.

**Comment by fabien** [comment]
Thanks @elbywan - I'm already using it, have a look here (WIP):

<img width="946" alt="example" src="https://user-images.githubusercontent.com/2749/31226583-eb8fd144-a9d6-11e7-9f54-83750056e1c2.png">

**Comment by elbywan** [comment]
Nice ! 👍

**Comment by fabien** [comment]
I'm now looking into having the checkmark icon be the only element to accept clicks for selection. I might be able to do that using strategies, no? Do you have any hints, perhaps?

**Comment by elbywan** [comment]
You can use `stopPropagation` to prevent selection bubbling.

Like this [fiddle](https://jsfiddle.net/elbywan/t414357q/)

**Comment by fabien** [comment]
I see, you're approaching it from a different perspective. I thought I could prevent the click event from a `click` strategy somehow. I'll try that, thanks!

**Comment by elbywan** [comment]
Nope, the click strategy does not work this way.

But you gave me an idea, I'll try something 😉 .

**Comment by fabien** [comment]
@elbywan I'm curious about your idea. What I've found is that your `stopPropagation` approach works, however, I would still like to unfold the node on click. I found a workaround (using the code from the `toggle-fold` click strategy), but it would be great to have a method to call for this purpose.

**Comment by elbywan** [comment]
@fabien Until now, a click would always select the item and trigger the selection strategies regardless of the click strategies.

Now the click strategies trigger the selection, which means that we can prevent unwanted item selection.

The downside is that if you override the default strategies object you now have to explicitely use the "select" click strategy to register a selection.

Now, for your use case, we can do this (I omitted the header and the model for better readability) :

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        /* ....... */
        <script src="https://cdnjs.cloudflare.com/ajax/libs/riot/3.7.3/riot+compiler.min.js"></script>
        <script src="/node_modules/@bosket/tools/bundle/tools.umd.min.js"></script>
        <script src="/node_modules/@bosket/core/bundle/core.umd.min.js"></script>
        <script src="/node_modules/@bosket/riot/bundle/riot.umd.min.js"></script>
        <style>
            .selected > span.item {
                color: red;
            }
        </style>
    </head>
<body>
    <script type="riot/tag">
        <wrapper>
            // Add a selector
            <span class="expander">{ opts.item.label }</span>
            <input type="checkbox" checked={ selected(opts.item) }/>

            selected(item) {
                return ~opts.inputs.selection.indexOf(item)
            }
        </wrapper>
        <root-app>
            <TreeView opts={ options } />

            // Import the click strategies
            const clickStrats = window["bosket-core"].clickStrategies
            // On click, filter by target
            const onclick = function(item, event, inputs) {
                if(event.target.className === "expander") {
                    // Expand the node without selection
                    clickStrats["toggle-fold"].bind(this)(item)
                } else {
                    // Otherwise, select the item
                    clickStrats["select"].bind(this)(item)
                }
            }
            this.options = {
                model:[ /* ....... */ ],
                category: "children",
                selection: [],
                onselection: function(_) {
                    this.options.selection = _
                    this.update()
                }.bind(this),
                strategies: { 
                    selection: ["multiple"], 
                    // The click strategy
                    click: [ onclick ], 
                    fold: ["opener-control"]
                },
                displaytag: _ => "wrapper"
            }
        </root-app>
    </script>
    <script>
        window.onload = () => riot.mount("*")
    </script>
    <root-app></root-app>
</body>
</html>
```

The [commit](https://github.com/elbywan/bosket/commit/a43267377b31281ce85ede81c39148d21faf89a5) is on the `develop` branch.

**Comment by fabien** [comment]
Awesome @elbywan you've been really helpful! Thanks!
