### ISSUE TITLE
Auto expand/open nodes on load

### ISSUE THREAD

**Issue by zenport** [elbywan/bosket#14]
I might have missed this in the docs, but how can I automatically open all nodes on initial load?

**Comment by elbywan** [comment]
You can do that by modifying the fold strategies :

```javascript
strategies: {
  /* ... */
  // permanently unfolds all nodes
  fold: [ () => false ]
  /* ... */
}
```

```javascript
strategies: {
  /* ... */
  // unfolds all nodes on load, then you can use the "opener" arrows to fold/unfold as usual
  fold: [ 
    function(item) {
        return array(this.state.get().unfolded).contains(item)
    }
  ]
  /* ... */
}
```

**Comment by zenport** [comment]
Thank you for the prompt reply. 

The permanent unfold example works fine, however, the second one gives me the following error.

`ReferenceError: array is not defined
    at TreeNode.TreeViewDemo._this.state.strategies.fold`

PS. I'm using the TreeView example with React.

**Comment by zenport** [comment]
works fine using the following strategy:

            fold: [
              function(item) {
                return (this.state.get().unfolded).includes(item)
              }
            ]

**Comment by elbywan** [comment]
Ah yes, sorry I forgot to add the array import !

`import { array } from @bosket/tools`

But if your browser supports Array.includes, it's even better 😉 .
Good to see that it worked !
