### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Offirmo** [elbywan/bosket#15]
Maybe it escaped me, but I couldn't see a demo on the website, nor a link in the GitHub readme.

That would be much appreciated!

**Comment by elbywan** [comment]
@Offirmo Did you check this [website](https://elbywan.github.io/bosket/react/#TreeView#Demo) ? There are multiple demos there 😉 .

**Comment by Offirmo** [comment]
Awesome! I sent a PR.

I'll keep bosket in my links, quite sure to use in in a personal project.

**Comment by Offirmo** [comment]
You should add a link on the site front page too: https://elbywan.github.io/bosket/ and that'll be perfect.
