### ISSUE TITLE
Clearing the search when starting drag

### ISSUE THREAD

**Issue by mleppik** [elbywan/bosket#18]
When using search, then it would be good to have the functionality to clear the search when starting a drag.

Version: Vue

Use case:
Users searches for a specific item. Initiates drag and wants to position the draggable element between two specific elements.
Problem: User cannot make the drop since the items aren't visible.

I tried just to clear the input but being Vue, the `$data.searchInput` doesn't change and therefore the tree doesn't update.

**Comment by elbywan** [comment]
>I tried just to clear the input but being Vue, the $data.searchInput doesn't change and therefore the tree doesn't update.

You can do that this way, just be sure to trigger an "input" event after clearing the "value" field and it should be allright !

I made a little [fiddle](https://jsfiddle.net/elbywan/9gro3pxv/) to demonstrate.

**Comment by mleppik** [comment]
Thank You! It didn't somehow occur to me to dispatch an input event from that element.
