### ISSUE TITLE
bosket + redux

### ISSUE THREAD

**Issue by iMaximal** [elbywan/bosket#19]
Hello!

Thank you for this component!

I'm trying to use it without a local state.

For example:

    const regions = this.props.regionsTree.regions;  // redux store

    const tree = {
      category: 'sub_regions', // name of the property containing the children
      selection: [],
      model: regions, // object for iterate
      display: (_) => _.region, // field for show
      onSelect: (newSelection, item, ancestors, neighbours) => {
        // newSelection     -> updated array containing all the selected items
        // item             -> the newly selected item (excluding the old one in case of multi selection)
        // ancestors        -> the ancestors of the newly selected item
        // neighbours       -> the neighbours of the newly selected item
        this.selection = newSelection;
      },
    };

    /* Drag'n'drop presets */

    const dragndrop = {
      // To drag or drop on specific items
      // you can use a function : (item) => true/false
      draggable: true,
      droppable: true,
      drag: null,  // action to perform on drag
      drop: null,  // action to perform on drop
      over: null,  // hook on dragover
      enter: null,  // hook on dragenter
      leave: null,  // hook on dragleave
      cancel: null,  // action to perform on cancellation
      guard: null,   // prevents dragover and drop
    };

        <TreeView
          {...tree}
          dragndrop={dragndrop}
          onSelect={tree.onSelect}
        />

Of course, drag'n'drop don't work (need describe action).

Do you have an example of using a TreeView with Redux?

**Comment by elbywan** [comment]
Hello @iMaximal !

Actually using bosket with redux should be quite straightforward.
Instead of storing the model/selection in your component state and call `setState()`, just `dispatch()` actions to your store.

I made a little fiddle to demonstrate : [bosket + redux](https://jsfiddle.net/elbywan/ue7eu1o2/)

Hope it will help :-)
