### ISSUE TITLE
how can i set checkBox options?

### ISSUE THREAD

**Issue by ghost** [elbywan/bosket#22]

**Comment by elbywan** [comment]
@iaruisana Hi !

Can you be a little more specific ?

**Comment by ghost** [comment]
Hi! just need select a node(s) with checkboxes

**Comment by elbywan** [comment]
You can try to do something like this : https://jsfiddle.net/elbywan/ny9nqe4r/

It's not perfect but it gives you an idea of how to add checkboxes !
