### ISSUE TITLE
model is undefined (in using computed property)

### ISSUE THREAD

**Issue by v1r0x** [elbywan/bosket#25]
Hey, it's me again 😅 
I'm trying to add a custom `children()` function, based on properties. Thus, I decided to use a `computed` property, which takes an input array and returns the same array, but with a `children()` function. This didn't work, so I stripped it down to the code of one of your examples (one entry with async children), but this didn't work too...Then, I moved if from `computed`, back to `data()` and everything works fine. Am I missing something or is it not intended to use `computed`?
Thanks in advance!

Edit: the error occurs when I click on the opener to show the children.

```javascript
[Vue warn]: Error in render: "TypeError: model is undefined"

found in

---> <TreeViewNode>
       <WithTransitionTreeViewNode>
         <TreeViewNode>
           <WithTransitionTreeViewNode>
             <TreeView>
               <WithLabelsTreeView>
                 <WithListenerWithLabelsTreeView>
                   <WithListenerWithListenerWithLabelsTreeView>
                     <TestTree> at resources/assets/js/components/TestTree.vue
                       <Root>
```

My Component:
```vue
<script>
    import { TreeView } from '@bosket/vue';

    export default {
        components: {
            'tree-view': TreeView
        },
        props: ['arr'],
        mounted() {},
        methods: {
            onSelect(newSelection) {
                this.selection = newSelection
            }
        },
        data() {
            return {
                selection: [],
                strategies: {
                    selection: ["single"],
                    click: ["select"],
                    fold: ["opener-control"]
                },
                category: "children",
                display: (item, inputs) => {
                    return item.label;
                }
            }
        },
        computed: {
            model() {
                return [{
                    name: "Asynchronous children",
                    children: () =>
                        new Promise(resolve =>
                            setTimeout(() =>
                                resolve([{ label: "It took exactly one second to fetch me the first time, I am cached afterwards." }]), 1000))
                }];
            }
        }
    }
</script>
```

**Comment by elbywan** [comment]
>Hey, it's me again 😅

Hello again 😉 

>Am I missing something or is it not intended to use computed?

Indeed this is not intended !
When using asynchronous children bosket will try to mutate the model on click to replace the Promise with the results of the Promise. If you used a computed property to get the model then bosket will be unable to find your model and mutate it.

**Comment by v1r0x** [comment]
Ok, thanks for your response. This saves me hours of further "debugging" :grin:
Since this is not a bug, I'm going to close this. Thanks!
