### ISSUE TITLE
Selecting/Opening/Closing nodes is really slow for large trees

### ISSUE THREAD

**Issue by bmitzkus** [elbywan/bosket#27]
Hey,

I am currently working on managing a large project with bosket (~500 root entries, 20k total entries). Although children are loaded asynchronically, any action (selecting/opening/closing nodes) on that tree takes several seconds. I suspect some sort of filter/map being applied to the whole tree on every action. Is there a way to avoid these loading times? I would really like to continue working with bosket =)

**Comment by stephanvierkant** [comment]
Same problem here with searching. My tree has around 4000 nodes and searching takes a couple of seconds.

**Comment by elbywan** [comment]
Sorry guys I really do not have a lot of free time this week, but I will for sure look into that as soon as I can !

I can tell you that I checked with a tree containing all the folders/files in my hard drive (the react [file explorer example](https://elbywan.github.io/bosket/react/index.html#Presets#ExplorerView)) and it seemed to be performing fine (except for the search bar which was a little bit slow). So there's hope 😉 .

It would also be extra helpful it you could tell me which framework you are using ? (react / angular / vue ... )

Thanks !

**Comment by stephanvierkant** [comment]
Thanks! 

I'm using Vue.

**Comment by bmitzkus** [comment]
Nice :)
I'm using Vue aswell

**Comment by bmitzkus** [comment]
Okay so I figured out that it has in fact nothing to do with bosket, but with the lookup of FontAwesome icons I used as opener. Sorry for causing trouble and thanks for putting time into it, closing this as it is resolved from my point of view. @stephanvierkant reopen if your issue is not related to FontAwesome.
