### ISSUE TITLE
Add options to search (delay, minimum length)

### ISSUE THREAD

**Issue by stephanvierkant** [elbywan/bosket#28]
I would like to add to features to the search box:

- Wait [...] milliseconds before searching to avoid the browser to search before the user has entered a search term.
- Set a minimum length of characters. It makes no sense to search for a single character in larger trees.

Any idea how to implement these features?

**Comment by elbywan** [comment]
@stephanvierkant Hi !

I've made a little fiddle with input debouncing & minimum characters length example [here](https://jsfiddle.net/elbywan/cmf6p6g4/).

Hope it will help, and sorry for the delay I have a lot on my plate these days 😉.
