### ISSUE TITLE
Better keyboard support (tab)

### ISSUE THREAD

**Issue by omnidan** [elbywan/bosket#29]
It would be nice if the tree view supported tabbing through items via the <tab> key.

**Comment by elbywan** [comment]
Hello @omnidan,

I think that you already can if you use the `tabindex` attribute in the rendered nodes, or if you use custom inputs like in this [fiddle](https://jsfiddle.net/elbywan/ny9nqe4r/).

Do you have something specific in mind ?

**Comment by omnidan** [comment]
@elbywan you are right, that is what I did and it works perfectly!
