### ISSUE TITLE
Module not found: Can't resolve 'react-transition-group/CSSTransitionGroup'

### ISSUE THREAD

**Issue by Gi972** [elbywan/bosket#3]
Hello,
I have a react configuration.

I try to install with a simple create app install and yarn install or npm install, after I put bosket in package.json, but I have the following error:

```
./~/bosket/react/traits/transitions.js
Module not found: Can't resolve 'react-transition-group/CSSTransitionGroup' in '/Users/j3di/Downloads/react-bosquet/node_modules/bosket/react/traits'

```
I try add react-transition-group in my package.json but it doesn't work..

my package.json configuration
```

{
  "name": "react-bosquet",
  "description": "",
  "dependencies": {
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-scripts": "1.0.10",
    "bosket": "0.2.1",
    "react-transition-group":"2.2.0"
  },
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}


```

**Comment by elbywan** [comment]
Ah yes, thanks for reporting this !

You have to install react-transition-group v1, not v2 :

`npm i react-transition-group@^1`

I will add a line in the documentation to highlight this dependency.
