### ISSUE TITLE
Custom search placeholder

### ISSUE THREAD

**Issue by thebesson** [elbywan/bosket#30]
It would be nice to have custom search placeholder, as current default one doesn't look very good with foreign language.

**Comment by elbywan** [comment]
>It would be nice to have custom search placeholder, as current default one doesn't look very good with foreign language.

Actually, it's possible already 😉 
See [documentation > optional properties > label](https://elbywan.github.io/bosket/react/index.html#TreeView#Optional%20properties#labels)

**Comment by thebesson** [comment]
Oh, nice! Thanks a lot!
