### ISSUE TITLE
Detecting fold/unfold click

### ISSUE THREAD

**Issue by jmguil** [elbywan/bosket#31]
Hello,
I'am using the VueJS version of bosket and I'am struggled with probably a stupid thing, how could i detect that a click on the opener has been made,  I knowh there is the onSelect method which is triggered when an item is selected, but i would like to know is if there is a way to have a kind of OnOpener method which would provide the state of  the node (fold/unfold) and the item corresponding to it but without selecting the item.

Thanks,
JM

**Comment by elbywan** [comment]
Hello @jmguil !

I've published a new version with a callback added when you click on an 'opener'.
Here's the documentation [link](https://elbywan.github.io/bosket/vue/index.html#TreeView#Optional%20properties#openerOpts) (optional properties > openerOpts) and also a little [fiddle](https://jsfiddle.net/elbywan/u4xzehr6/) example.

Hope it will help 😉 .

**Comment by jmguil** [comment]
Hello,
Fantastic ! Thanks for your reactivity :-) 
I will try that today.
