### ISSUE TITLE
don't render opener symbol for empty children arrays

### ISSUE THREAD

**Issue by BegeMode** [elbywan/bosket#35]
we have in core/logic.js:

`_this.hasChildren = function (item) {
            return item[_this.inputs.get().category] && item[_this.inputs.get().category] instanceof Array;
 }
`

it's possible to make one more check for array's length?

`_this.hasChildren = function (item) {
            return item[_this.inputs.get().category] && item[_this.inputs.get().category] instanceof Array && item[_this.inputs.get().category].length;
        }`

**Comment by elbywan** [comment]
Hey @BegeMode,

I cannot change this line in the `logic.js` file since `hasChildren` is not only used for cheking if `bosket` should render the opener.

But, I changed the renderOpener method to hide it for empty folders 😉.

**Comment by BegeMode** [comment]
Thank you, you have made a superb treeview component.
