### ISSUE TITLE
Vue JS - Is it possible to pass in a single file component as a display item?

### ISSUE THREAD

**Issue by ty-fleming** [elbywan/bosket#37]
`  display: item => <folder-tree-item v-bind:folder="item" v-bind:email-account="this.emailAccount" v-bind:parent-folder-name="item.RawFolderName" ></folder-tree-item>,`

I'm curious if its possible to render another component in the display function. 

Thanks!

**Comment by ty-fleming** [comment]
Nevermind I figured it out. I was able to accomplish it by using this.$createElement().

Heres the tree view
`<tree-view :model="folderList"
                       category="Folders"
                       :selection="selection"
                       :onSelect="onSelect"
                       :display="displayItem"
                       :strategies="strategies"
                       :openerOpts="openerOpts"
                       :search="search"
                       :css="css">
            </tree-view>`


Here's my display function
` displayItem: function (item) {
                return this.$createElement(FolderTreeItem, {
                    props: {
                        folder: item,
                        emailAccount: this.emailAccount,
                        parentFolderName: item.RawFolderName,
                        moveActivated: this.moveActivated
                    }
                })
            },`

**Comment by elbywan** [comment]
Great! Thanks for posting the solution here 😉 (note that you can also use [`jsx`](https://vuejs.org/v2/guide/render-function.html) instead of using `$createElement` yourself)
