### ISSUE TITLE
Drag on same level

### ISSUE THREAD

**Issue by Gi972** [elbywan/bosket#40]
Hello @elbywan ,

First your tool is very very awesome thanks for this simple and easy to use.

I need your help for the drag and drop.

I want drag element but only with the same level between the source Item and the destination Item.

I try Many solutions, but I don't arrive drag only the same element with the same level or  except when a specific properties in model allowIt , specialy with async element.
Also it's possible to open automatically the children when I drag element over it?

You can see the model here: https://stackblitz.com/edit/react-zasmjr?file=model.js

all elements have a level.

Thanks for your help

**Comment by jmoseman01** [comment]
https://github.com/elbywan/bosket/issues/44

**Comment by Gi972** [comment]
Thanks @jmoseman01,

I solve my issue by overriding the drag and drop method.

I close this
