### ISSUE TITLE
Drag and Drop inbetween nodes (re-order nodes)

### ISSUE THREAD

**Issue by jmoseman01** [elbywan/bosket#44]
Is there a way to drag and drop where you can change the order of sibling nodes?

**Comment by jmoseman01** [comment]
I'm trying to do this in angular.

**Comment by elbywan** [comment]
Can you check issue #4 ? I gave an example for React, I cannot write the full code for every framework.

The basic idea is to use this custom drop function :

```js
dragndrop: {
      // Use the "selection" drag and drop preset
      ...selectionPreset,
      drop: (item, event, inputs) => {
        // If we drop on a placeholder, reorder
        if(item && event.target.className === "order-placeholder") {
          inputs.model.forEach((elt, index) => {
            elt.order = index
            if(elt.order >= item.order) elt.order++
          })
          inputs.selection[0].order = inputs.model.indexOf(item)
          // Drop on ancestor
          selectionPreset.drop(inputs.ancestors[inputs.ancestors.length - 1], event, inputs)
        } else {
          selectionPreset.drop(item, event, inputs)
        }
      },
    }
```

Combined with the fact that you display a custom component with an 'order-placeholder' class.
Check [the documentation > optional properties > displayComponent](https://elbywan.github.io/bosket/angular/index.html#TreeView#Optional%20properties#displayComponent) to see how to use a component for each item in the tree.

Your component template should be something that looks like: 
```
template: `
<div>
   <a>{{ item.label }}</a>
   <span class="order-placeholder">reorder</span>
</div>`
```

Sorry I don't have the time to write the full fiddle, hope this will help!
