### ISSUE TITLE
Tree doesn't reset when search field is emptied

### ISSUE THREAD

**Issue by fabien** [elbywan/bosket#5]
When testing the Riot demo, there's a native `type="search"` (x) button when the search field has a value. However, clicking on it doesn't reset the tree display, it only empties the field itself. Perhaps a different event (like `input`) should be used?

**Comment by elbywan** [comment]
Hi @fabien,

I don't know why (surely an overlook) but I used the `keyup`event in riot and the `input`event in the other frameworks.

I'm fixing this asap, thanks for raising the issue !
