### ISSUE TITLE
Expose nodeEvents

### ISSUE THREAD

**Issue by tyler1314371** [elbywan/bosket#7]
Hi,

I am just wondering if there is a way to expose/use `nodeEvents` in `bosket/src/core/dragndrop.js`?
What I am trying to do is to show different animation on drag enter and drag leave in a sortable tree.

Thanks,

**Comment by elbywan** [comment]
> I am just wondering if there is a way to expose/use nodeEvents in bosket/src/core/dragndrop.js?

I just added <a href="https://elbywan.github.io/bosket/react/index.html#TreeView#Optional properties#dragndrop">some hooks</a> to execute custom actions on dragover/enter/leave. 
You could use them to add/remove css classes if you want to.

Angular example : 

```typescript
const onEnter = ({event}) => event.currentTarget.style.color = "red"
const onLeave = ({event}) => event.currentTarget.style.color = "blue"

<TreeView /*...*/ (onEnter)="onEnter($event)" (onLeave)="onLeave($event)"></TreeView>
```

For react/vue/riot the callbacks are set in the dragndrop object prop.
