### ISSUE TITLE
Drag and drop reordering

### ISSUE THREAD

**Issue by fabien** [elbywan/bosket#9]
The demo uses a custom sort function, so I was expecting that without that you'd be able to reorder nodes amongst siblings. However, this doesn't seem to be possible - I can only change the hierarchy/nesting, not simply reorder these items.

Would it be possible to add this (as a flag, perhaps)?

**Comment by elbywan** [comment]
Can you check issue #4 ?

I gave an example with react, but for riot it should quite the same.

**Comment by fabien** [comment]
Oops! I didn't see that! I was able to implement this, and it's close to what I was hoping for. It's currently not working for leaf nodes though - they never get a `.dragover` class during dragging.

**Comment by elbywan** [comment]
I will check it out tomorrow !

**Comment by elbywan** [comment]
>they never get a .dragover class during dragging.

Indeed, found out that you have to prevent riot from refreshing the dom on dragover when using a custom displaytag.

I came up with a little snippet which should work :

```javascript
<orderable-tree>
  <TreeView opts={ options } />

  riot.tag("wrappedlabel", '<div><a>{ opts.item.label }</a><span class="order-placeholder">reorder</span></div>')
  var selectionPreset = bosket.dragndrop.selection(() => this.options.model, m => this.options.model = m)

  this.options = {
    // regular options
    model: [
      { label: 1, children: [
        { label: 2 }, { label: 3 }, { label: 4 }
      ]},
      { label: 5, children: [
        { label: 6 }, { label: 7 }, { label: 8 }
      ]}
    ],
    category: "children",
    selection: [],
    onselection: _ => {
      this.options.selection = _
      this.update()
    },
    strategies: { selection: ["single"], /* and for clarity : */ fold: [ _ => false ]},
    // Custom display tag
    displaytag: item => "wrappedlabel",
    // Sort by order
    sort: (a, b) => a.order - b.order,
    dragndrop: {
      // Use the "selection" drag and drop preset
      ...selectionPreset,
      drop: (item, event, inputs) => {
        // If we drop on a placeholder, reorder
        if(item && event.target.className === "order-placeholder") {
          inputs.model.forEach((elt, index) => {
            elt.order = index
            if(elt.order >= item.order) elt.order++
          })
          inputs.selection[0].order = inputs.model.indexOf(item)
          // Drop on ancestor
          selectionPreset.drop(inputs.ancestors[inputs.ancestors.length - 1], event, inputs)
        } else {
          selectionPreset.drop(item, event, inputs)
        }
        this.update()
      },
      // prevents riot dom refresh !
      over: (_, event) => event.preventUpdate = true
    }
  }
</orderable-tree>
```

**Comment by fabien** [comment]
I haven't tried this yet, I will have a look tomorrow. Thanks!

**Comment by elbywan** [comment]
Hi @fabien, any news ?

I made a fiddle to test the code, seems to be working just fine : [fiddle](https://jsfiddle.net/elbywan/2zy31zre)

**Comment by fabien** [comment]
Hi @elbywan thanks for the fiddle update! I've been busy updating my app to the latest Riot version (I was stuck with an old version that wasn't compatible with bosket). I did test your example (isolated from my app), but I was having some issues.

With the help of your fiddle, I should be fine though!

**Comment by elbywan** [comment]
Allright, thanks for the feedback !

I'm closing the issue, feel free to reopen it if you have any more trouble about tree ordering !

**Comment by fabien** [comment]
It appears that leaf nodes currently cannot become a parent (~ category) by dragging a child on top of it (not on the reorder placeholder). Is this a limitation, or can this be tuned using the `guard` callback?

Another thing I noticed: the `dropEffect` seems to be limited to `moveCopy` or something, because it will always display a plus icon next to the dragging cursor. I tried to set it to `move` but it stopped working altogether it seems (perhaps the 'copy' is associated with the JSON being moved?).

**Comment by elbywan** [comment]
>It appears that leaf nodes currently cannot become a parent (~ category) by dragging a child on top of it (not on the reorder placeholder). Is this a limitation, or can this be tuned using the guard callback?

To turn a child into a parent, just add an empty array children property :
```js
// If we drop on a leaf, make it a parent
if(!item.children)
    item.children = []
```

Check this [fiddle](https://jsfiddle.net/elbywan/o5Lqbqs4/).

>Another thing I noticed: the dropEffect seems to be limited to moveCopy or something

Unfortunately, I think there is nothing I can do about this. That it's just how the major browsers implemented the html5 dragndrop api :(. Mouse cursor normally should change according to the spec, but on my mac for chrome/safari/firefox it only adds a green plus sign for the "copy" dropEffect. The other ones have no influence.
